# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Offers' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Offers
  pod 'NSHash', '~> 1.2.0'

  target 'OffersTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OffersUITests' do
    # Pods for testing
  end

end
post_install do |installer|
  installer.pods_project.targets.each do |target|
    puts "#{target.name}"
  end
end
